### ISSUE TITLE
Error parsing of tesseract output is brittle: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by barik** [madmaze/pytesseract#32]
When using python 3.5 and [pillow](https://pypi.python.org/pypi/Pillow/3.1.1) (the original PIL library is quite old now), I receive an error on this very simple example:

``` python
import pytesseract

try:
    import Image
except ImportError:
    from PIL import Image

pytesseract.image_to_string(Image.open('test_image.png'))
```

The error is:

```
Traceback (most recent call last):
  File "tesseract_test.py", line 8, in <module>
    pytesseract.image_to_string(Image.open('test_image.png'))
  File "C:\Users\tbarik\AppData\Local\Programs\Python\Python35\lib\site-packages\pytesseract\pytesseract.py", line 163, in image_to_string
    errors = get_errors(error_string)
  File "C:\Users\tbarik\AppData\Local\Programs\Python\Python35\lib\site-packages\pytesseract\pytesseract.py", line 111, in get_errors
    error_lines = tuple(line for line in lines if line.find('Error') >= 0)
  File "C:\Users\tbarik\AppData\Local\Programs\Python\Python35\lib\site-packages\pytesseract\pytesseract.py", line 111, in <genexpr>
    error_lines = tuple(line for line in lines if line.find('Error') >= 0)
TypeError: a bytes-like object is required, not 'str'
```

I'm using Windows 10, 64-bit, with python x64.

**Comment by barik** [comment]
Okay, it seems like the problem isn't related to Pillow at all. There actually is an error in `tesseract.` But on the Python end the error occurs because `error_string` is returning a byte-literal, and the `geterrors` call appears to have trouble with it.

```python
status, error_string = run_tesseract(input_file_name,
                                             output_file_name_base,
                                             lang=lang,
                                             boxes=boxes,
                                             config=config)
```

**Comment by doomzhou** [comment]
same error in archliux

**Comment by GelaniNijraj** [comment]
Anyone found a workaround?

**Comment by GelaniNijraj** [comment]
Installing the training data for particular language as shown [here](http://stackoverflow.com/a/22801937/4997836) solves the problem.

**Comment by avindra** [comment]
@GelaniNijraj : Thank you, that works perfectly.

**Comment by z3ntu** [comment]
In Arch Linux you have to install the package `tesseract-data-<lang>` eg `tesseract-data-eng` for english.

**Comment by john-francis96** [comment]
The error is an issue with pytesseract - not with the language pack. Essentially there is an encoding conflict in python3 when errors are returned from the console. I fixed it in pull request #48 which hasn't been merged as of yet.

**Comment by zwl1619** [comment]
I have download the training data into `C:\Program Files (x86)\Tesseract-OCR\tessdata`,like this:

[![enter image description here][1]][1]


  [1]: https://i.stack.imgur.com/TwwEo.png

but the error still exists.

**Comment by 400yk** [comment]
I had the same problem but now with a little fix of the pytesseract.py the problem is resolves. The error occurs because we didn't set the environment variable TESSDATA_PREFIX in the subprocess. Therefore, in the pytesseract.py file, under the function "run_tesseract", add

my_env = {"TESSDATA_PREFIX":"/opt/local/share"}

(for me the /opt/local/share is the parent folder that contains tessdata, plz change accordingly)

Then in the same function change the "proc=..." to

    proc = subprocess.Popen(command, env=my_env,
            stderr=subprocess.PIPE)


Lastly, at the beginning of the file, change the definition of tesseract_cmd to:

tesseract_cmd = '/opt/local/bin/tesseract'

(namely to specify the absolute path, if you aren't sure, can go to shell and enter "which tesseract" to find out).

Good luck!

**Comment by unnir** [comment]
Ubuntu, Python3.5, same issue, I have the training data.

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-9eeca5e48ef3> in <module>()
----> 1 pytesseract.image_to_string(image)

/home/borisov/anaconda3/lib/python3.5/site-packages/pytesseract/pytesseract.py in image_to_string(image, lang, boxes, config)
    161                                              config=config)
    162         if status:
--> 163             errors = get_errors(error_string)
    164             raise TesseractError(status, errors)
    165         f = open(output_file_name)

/home/borisov/anaconda3/lib/python3.5/site-packages/pytesseract/pytesseract.py in get_errors(error_string)
    109 
    110     lines = error_string.splitlines()
--> 111     error_lines = tuple(line for line in lines if line.find('Error') >= 0)
    112     if len(error_lines) > 0:
    113         return '\n'.join(error_lines)

/home/borisov/anaconda3/lib/python3.5/site-packages/pytesseract/pytesseract.py in <genexpr>(.0)
    109 
    110     lines = error_string.splitlines()
--> 111     error_lines = tuple(line for line in lines if line.find('Error') >= 0)
    112     if len(error_lines) > 0:
    113         return '\n'.join(error_lines)

TypeError: a bytes-like object is required, not 'str'`
